# Generated by Django 3.2.8 on 2021-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('unrz', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='unrz')),
                ('fio', models.CharField(max_length=150, verbose_name='Ф*И*О*')),
                ('birthdate', models.DateField(verbose_name='ДР')),
                ('doc', models.CharField(max_length=20, verbose_name='Ф*И*О*')),
                ('stuff', models.CharField(max_length=250, verbose_name='Вакцина')),
                ('singlePhase', models.CharField(max_length=1, verbose_name='Ф')),
                ('qr', models.TextField(verbose_name='QR')),
                ('expiredAt', models.DateField(verbose_name='До')),
                ('status', models.CharField(max_length=1, verbose_name='Ф')),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
