# Generated by Django 3.2.8 on 2021-10-30 10:03

from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20211027_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='n',
            field=models.IntegerField(null=True, verbose_name='n'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='r',
            field=models.IntegerField(null=True, verbose_name='r'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='qr_url',
            field=models.CharField(max_length=250, null=True, verbose_name='url'),
        ),
        migrations.RunSQL('update hello_stuff set r = unrz / 10000000000000 , n = unrz % 10000000000000',
            migrations.RunSQL.noop,
        )
    ]
