# Generated by Django 3.2.8 on 2021-11-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20211030_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
